### ISSUE TITLE
Installer exits without allowing user input if sandbox is already installed

### ISSUE THREAD

**Issue by jmoody** [calabash/install#17]
```
$ curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash
Sandbox already exists! Do you want to overwrite? (y/n)
moody@stern:~
```

**Comment by sapieneptus** [comment]
Well, to be fair, the `README` says that if you're trying to re-install, you should first 
```shell
rm -r ${HOME}/.calabash/sandbox
```
before running that. 

However, if you prefer, we can change the one-liner to:
```shell
curl -O https://raw.githubusercontent.com/calabash/install/master/install-osx.sh && chmod a+x install-osx.sh && ./install-osx.sh
```

That will ensure the user gets a chance to respond to the prompt. I was just hoping to keep the command shorter.

**Comment by sapieneptus** [comment]
On that note, @jmoody do you feel it's necessary to prompt for overwrite? I thought it might be safer initially, but I'm not 100% sold that it's even necessary.

**Comment by jmoody** [comment]
> necessary

I _think_ we should just overwrite.  There is no harm correct?  And we need want a smooth upgrade-path for users.

**Comment by sapieneptus** [comment]
There's sort of harm - 

Imagine the user has installed a bunch of gems in the sandbox. I _believe_ the script will overwrite that dir if you try to `install` over it.

**Comment by jmoody** [comment]
Doesn't the original installer block for user input?

Maybe we can change text?  What is the use case _for asking?_  Why not just fail with a message like "Detected an install; you have to remove it first."?

**Comment by jmoody** [comment]
Another case where the prompts should work.

The problem is that it is not clear to user how to resolve the issue if they want a _clean_ install.

For example, I could clear this by changing the group and permissions on /usr/local but even I did not know how to _uninstall_ and re-install.


```
######################################################################## 100.0%
Preparing sandbox...
######################################################################## 100.0%
override rwxr-xr-x  jenkins/admin for /usr/local/bin/calabash-sandbox? (y/n [n]) not overwritten
```

**Comment by Krumelur** [comment]
My thoughts on this since I just hit the same issue: I was surprised first to to the script asking me for yes or no but I'm unable to do anything.
I'd love to see a warning ("you might have installed gems") and then decide if I want to nuke it and reinstall.

**Comment by jmoody** [comment]
The original script _did_ block for user input.
