### ISSUE TITLE
Cannot run bundle update: SSL errors

### ISSUE THREAD

**Issue by jmoody** [calabash/install#37]
I was working with a user via tmate and he was using system ruby.  I wanted to verify that the unit tests would run with his changes.

I later reproduced on a clean account on the Calabash iOS machine.

```
Gem::RemoteFetcher::FetchError: SSL_connect returned=1 \
  errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

### Reproduce:

Cannot be reproduced if you have rbenv installed; the sandbox does not override the ruby path.

```
# Create a clean account or ssh to your account
$ ssh yourname@calabash-ci.maciminicolo.net

# Clone calabash-ios
$ mkdir -p tmp
$ cd tmp
$ git clone https://github.com/calabash/calabash-ios.git
$ cd calabash-ios/calabash-cucumber

# install sandbox
$ curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash

$ calabash-sandbox
$ bundle update
```

### Expected

To be able to update the bundle for the calabash-ios gem.

### Found

For every gem bundler tried to install:

```
Gem::RemoteFetcher::FetchError: SSL_connect returned=1
```

### Notes

1. The SSL cert in the pre-packaged ruby might be to blame.
2. We might be relying on an old version of the `rubygems` gem. If we are not doing so already, we should be installing rubygems as part of the sandbox and using the `gem` binary from that install.

**Comment by sapieneptus** [comment]
@jmoody I didn't realize there's an SSL cert inside of ruby? The version of `gem` is bundled with the Ruby, but I would assume that should just work, no? 

I'll do some digging. Would love to nip this one.

**Comment by lynxluna** [comment]
I manage to do using these steps in [from here](https://gist.github.com/luislavena/f064211759ee0f806c88). The difference is, instead of using the system ruby we need to go inside calabash sandbox first.

```console
% calabash-sandbox
```

and then obtain the trust store directory obtained from this command

```console
% gem which rubygems
```

I manage to put together a small one liner

```sh
OUTPUT_DIR=`gem which rubygems | xargs dirname`/rubygems/ssl_certs \
  curl --progress-bar -o "${OUTPUT_DIR}/AddTrustExternalCARoot-2048.pem"  \
  https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/AddTrustExternalCARoot-2048.pem
```

After that `calabash-sandbox update` should work.

**Comment by jonstoneman** [comment]
The Windows sandbox had this issue and I had manually added `AddTrustExternalCARoot-2048.pem` to the ruby zip in the location shown in @lynxluna's shell script.  This was only required with ruby 2.1.5 however and we're now using 2.1.6 on Windows and it includes the cert.

**Comment by sapieneptus** [comment]
@lynxluna Thanks!

@jmoody So what do you think? We could add @lynxluna 's script to the sandbox as part of install, or we could switch to Ruby 2.1.6 and no longer match XTC ... @krukow  do you happen to know if Ruby 2.1.6 vs 2.1.5 would cause significant issues?

**Comment by jmoody** [comment]
@sapieneptus 

+1 for 2.1.6.

**Comment by sapieneptus** [comment]
Trying to verify whether 2.1.5 vs 2.1.6 will cause any issues w/re:to XTC - once I hear back, I'll make a change accordingly.

**Comment by krukow** [comment]
2.1.6 is fine

**Comment by sapieneptus** [comment]
@lynxluna Can you give [this](https://github.com/calabash/install/pull/38) branch a try? It's using ruby 2.1.6.

@jmoody I _think_ I have an account on the jenkins machine, but I recall that it may screw something up if I log in. Is there another way to repro?

**Comment by jmoody** [comment]
@sapieneptus You can create a new user on your local machine.

**Comment by jmoody** [comment]
Good job.

**Comment by jmoody** [comment]
And thanks @lynxluna!  We don't have release notes or a changelog for this repo.  If we did, I would give you an attribution.
