### ISSUE TITLE
Error trying to use sandbox on Windows

### ISSUE THREAD

**Issue by topgenorth** [calabash/install#40]
Just received this from the Docs Feedback dashboard about a potential issue using the sandbox on Windows. This is the report, verbatim:

> Using the Calabash Sandbox on Windows sample code problem
> 
> Getting this Error: iex : You cannot call a method on a null-valued expression. At line:1 char:133 + ... > ubusercontent.com/calabash/install/master/install-windows.ps1") | iex Is there any fix to this??

Screenshot of the feedback: 

![screenshot 2016-01-25 08 21 58](https://cloud.githubusercontent.com/assets/10829/12555103/c6bd1dcc-c33c-11e5-8c57-4bf3e95faea9.png)

FWIW, I could not duplicate the problem on my Windows 10 VM.

**Comment by jonstoneman** [comment]
It would be really helpful if they could they try running this and providing the output?

```(New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/calabash/install/master/install-windows.ps1")```

To get the sanbox installed they could try downloading [the install script](https://raw.githubusercontent.com/calabash/install/master/install-windows.ps1) and running it in powershell manually.

**Comment by topgenorth** [comment]
Sadly, the docs feedback tools doesn't allow for a way to contact the user. Figured it would be worth logging this in case a "proper" bug report is raised.

**Comment by topgenorth** [comment]
This appeared again on the Docs Feedback. Unfortunately I have no way of contacting the user or knowing if it is the same user or not.

>iex : You cannot call a method on a null-valued expression. At line:1 char:133 + ... > ubusercontent.com/calabash/install/master/install-windows.ps1") | iex + ~~~ + CategoryInfo : InvalidOperation: (:) [Invoke-Expression], RuntimeException + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by jonstoneman** [comment]
Hopefully solved in PR https://github.com/calabash/install/pull/41.  I know you can't respond to users but in case anyone finds this issue and the fix hasn't been merged then the new version of the script can be run using:

```
(New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/calabash/install/windows/donet_unzip/install-windows.ps1") | iex
```

**Comment by topgenorth** [comment]
Just to keep this up to date, it seem that some users are now reporting problems (to which @sapieneptus  has replied) on the forums - [Error trying to install Calabash sandbox on Windows](http://forums.xamarin.com/discussion/59730/error-trying-to-install-calabash-sandbox-on-windows).

**Comment by sapieneptus** [comment]
On the forum, I've only just parroted @jonstoneman 's advice - hopefully that's enough to resolve it. We are still doing some tests internally.

**Comment by jonstoneman** [comment]
I've just merged the updated install script so will close this issue.
