### ISSUE TITLE
Getting an error while trying to install Calabash.

### ISSUE THREAD

**Issue by subinrevi** [calabash/install#50]
Attaching the screenshot of the terminal. Running the following command.

When running "calabash-iso gen" command not found error is shown.

curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash
![screen shot 2016-03-17 at 5 29 02 pm](https://cloud.githubusercontent.com/assets/8567369/13845465/23cb2f48-ec66-11e5-9782-aa1c3a485e9f.png)

**Comment by jmoody** [comment]
@subinrevi 

Sorry it took so long to get back to you.

We cannot reproduce.

Can you try again?

There is a bug here - we should be failing on SSL errors.

Is it possible you are using the non-Apple version of OpenSSL or you are behind a firewall?

```
$ which OpenSSL
/usr/bin/OpenSSL
$ OpenSSL version
OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by jmoody** [comment]
The bug here is that script does not detect the download failure.

We have tried to reproduce the SSL failure on several machines, but have been unable to do so.
