### ISSUE TITLE
Warn Windows users about spaces in the path.

### ISSUE THREAD

**Issue by topgenorth** [calabash/install#53]
This was received by Docs via our feedback portal:

> Install script path defaults to current user's folder eg "c:\users\a user". The space in this path causes calabash-android run command to error. Please annotate the installer script with instructions to change path

I can update the docs, but it might be handy to update the Windows installer script so that it lets the users know about spaces in the path.

**Comment by jonstoneman** [comment]
I've modified calabash-android so that `run` can handle user folders containing spaces:  https://github.com/calabash/calabash-android/pull/713
