### ISSUE TITLE
make publish_osx should update bin/test/sandbox_test.sh

### ISSUE THREAD

**Issue by sapieneptus** [calabash/install#57]
Currently, if you do `make publish_osx` and it updates any of the gems and you try to commit that, it will fail because the tests are still checking against old versions. We should have `make publish_osx` automatically update `bin/test/sandbox-test.sh` to check for the correct version. It just needs to rewrite an env var in the script.

**Comment by jmoody** [comment]
We are no longer publishing a CalabashGems.zip.  The installer uses bundler to install the required gems.  Users who want the latest gems should either:

1. use `rbenv`
2. use bundler + Gemfile in their project
3. delete the existing sandbox and reinstall
