### ISSUE TITLE
Cannot install calabash sandbox on macOS: cannot load such file -- rubygems.rb 

### ISSUE THREAD

**Issue by MSI15** [calabash/install#65]
Following execution of the following code I am getting an error and Calabash Sandbox installation fails:

curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash

```

Preparing Ruby 2.3.1...
######################################################################## 100.0%
Installing gems, this may take a little while...
######################################################################## 100.0%
Preparing sandbox...
######################################################################## 100.0%
Done! Installed:
calabash-ios:       <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
calabash-android:   <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
xamarin-test-cloud: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
Execute 'calabash-sandbox update' to check for gem updates.
Execute 'calabash-sandbox' to get started!
```

**Comment by atteeela** [comment]
+1

**Comment by vfennerac** [comment]
Same issue here, I even removed my RVM installation fully just to be sure.

**Comment by icy1007** [comment]
I am having the same issue. I am unable to run Calabash tests now that the sandbox is not installing/updating correctly.

```
$ calabash-sandbox update
Updating gems...
<internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

Done! Now the sandbox contains:
calabash-ios:       <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
calabash-android:   <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
xamarin-test-cloud: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

**Comment by jameshuangg** [comment]
+1 same issue here
Preparing Ruby 2.3.1...
##################################################################### 100.0%
Installing gems, this may take a little while...
##################################################################### 100.0%
Preparing sandbox...
##################################################################### 100.0%
Done! Installed:
calabash-ios:       <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
calabash-android:   <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
xamarin-test-cloud: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
Execute 'calabash-sandbox update' to check for gem updates.
Execute 'calabash-sandbox' to get started!

**Comment by icy1007** [comment]
I've fixed this temporarily by modifying the install scripts and the calabash-sandbox executable to go back to using ruby 2.1.6-p336.

**Comment by mauriziopinotti** [comment]
@icy1007 can you please elaborate more? I've downloaded install-osx.sh and modified CALABASH_RUBY_VERSION="2.1.6-p336"

this seems to fix the sandbox installation but the json gem fails to install:

```
calabash-ios:       /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'json' (~> 1.8) - did find: [json-1.7.7] (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /Users/Ajeje/.calabash/sandbox/Gems/bin/calabash-ios:22:in `<main>'
calabash-android:   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'json' (~> 1.8) - did find: [json-1.7.7] (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /Users/Ajeje/.calabash/sandbox/Gems/bin/calabash-android:22:in `<main>'
xamarin-test-cloud: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'json' (~> 1.8) - did find: [json-1.7.7] (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /Users/Ajeje/.calabash/sandbox/Gems/bin/test-cloud:22:in `<main>'
```

and the update gives

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
extension.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
extconf.rb
creating Makefile

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10:
fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
1 error generated.
make: *** [generator.o] Error 1


Gem files will remain installed in
/Users/Ajeje/.calabash/sandbox/Gems/gems/json-1.8.3 for inspection.
Results logged to
/Users/Ajeje/.calabash/sandbox/Gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

Thanks!

**Comment by icy1007** [comment]
@mauriziopinotti I modified line 15 of the install script to read:
`CALABASH_RUBY_VERSION="2.1.6-p336"`
and commented out lines 70 through 86 as I already had the calabash-sandbox unix executable installed.

I then opened up the calabash-sandbox unix executable in a script editor and modified line 42 to read:
`CALABASH_RUBY_VERSION="2.1.6-p336"`
and line 46 to read:
`export GEM_PATH="${CALABASH_GEM_HOME}:${CALABASH_GEM_HOME}/ruby/2.0.0:${CALABASH_GEM_HOME}/ruby/2.1.0"`

I hosted my modified "install-osx.sh" file locally via an http daemon and ran this command via terminal:
`curl -sSL {local IP Address}/install-osx.sh | bash` 

It installed the sandbox fine and I can now run calabash-ios through the sandbox, but I get an error when attempting to update the sandbox:

`$ calabash-sandbox update
Updating gems...
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using awesome_print 1.7.0
Using builder 3.2.2
Using bundler 1.13.6
Using gherkin 4.0.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.2.5
Using multi_json 1.12.1
Using multi_test 0.1.2
Using escape 0.0.4
Using retriable 2.0.2
Using rubyzip 1.2.0
Using clipboard 1.1.1
Using edn 1.1.1
Using command_runner_ng 0.1.0
Using i18n 0.7.0
Using mime-types 2.99.3
Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate B: certificate verify failed
(https://rubygems.org/gems/CFPropertyList-2.3.4.gem)
An error occurred while installing CFPropertyList (2.3.4), and
Bundler cannot continue.
Make sure that `gem install CFPropertyList -v '2.3.4'` succeeds before
bundling.

Done! Now the sandbox contains:
calabash-ios:       0.20.3
calabash-android:   0.8.4
xamarin-test-cloud: 2.1.0`

**Comment by atteeela** [comment]
Ive found a workaround:

curl -sSL https://raw.githubusercontent.com/calabash/install/27781b823f0c34e43d0a336664420347b762ff52/install-osx.sh | bash

Tested to work fully

**Comment by icy1007** [comment]
I was able to resolve my error I posted above by updating rubygems in the sandbox:
http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

**Comment by timpactera** [comment]
Getting the same issue. The workaround from atteeela not working for me.

**Comment by jayczech23** [comment]
@atteeela solution works great! Thank you.

**Comment by jmoody** [comment]
Fixed by #68

I strongly recommend that you start using `rbenv`.

**Comment by matteocollina** [comment]
@atteeela I can install calabash-sandbox but when i enter the command on the terminal: : 
"Calabash-sandbox is only supported on macOS El Cap and Sierra"

**Comment by jmoody** [comment]
This product is no longer support.

Use rbenv.

**Comment by matteocollina** [comment]
@jmoody is there a tutorial that explains how to execute "calabash-sanbox" command, likes in the [Xamarin docs](https://developer.xamarin.com/guides/testcloud/calabash/quickstarts/xcode/linking-the-calabash-framework/) ?

**Comment by jmoody** [comment]
You should not use this product.

**Comment by matteocollina** [comment]
@jmoody can you have more explanations about your answer? thank you.

**Comment by alessandro-aglietti** [comment]
@jmoody with "this product" you mean calabash or calabash sandbox or both?

thank you very much

**Comment by jmoody** [comment]
> can you have more explanations about your answer? thank you.

It is not worth our time trying to provide a ruby environment for macOS when other products can do it better.  rbenv + Gemfile + bundler.

> "this product"

The sandbox.

It says so in the README:

>> The calabash-sandbox tool is no longer maintained. You can still use the sandbox, but the ruby version and the base Gemfile will not be updated. To keep your gems up to date, use bundler and Gemfile.
