### ISSUE TITLE
First line of gem file is hardcoded ruby location to "#!/Users/moody/Downloads/ruby-2.3.1/install-directory/bin/ruby"

### ISSUE THREAD

**Issue by saraporter** [calabash/install#66]
Path is ~/.calabash/sandbox/Rubies/2.3.1/bin/gem

When trying to run gem update or other commands, the error is 
calabash-sandbox]$ gem update
bash: /Users/saraporter/.calabash/sandbox/Rubies/2.3.1/bin/gem: /Users/moody/Downloads/ruby-2.3.1/install-directory/bin/ruby: bad interpreter: No such file or directory

**Comment by jmoody** [comment]
Fixed by #68

I strongly recommend you start using rbenv.
