### ISSUE TITLE
Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by zwiebelspaetzle** [calabash/install#69]
When I try to install calabash sandbox on El Capitan, I get an error with _clock_gettime.  It appears that it's trying to use a file built for Sierra.

OS X v10.11.6
XCode v8.2.1

Output:
$ curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bashPreparing Ruby 2.3.1...
######################################################################## 100.0%
Installing gems, this may take a little while...
######################################################################## 100.0%
Preparing sandbox...
######################################################################## 100.0%
Done! Installed:
calabash-ios:       dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

bash: line 1: 27832 Trace/BPT trap: 5       calabash-ios version 1>&2
calabash-android:   dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

bash: line 1: 27743 Trace/BPT trap: 5       calabash-android version 1>&2
xamarin-test-cloud: dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/cward/.calabash/sandbox/Rubies/2.3.1/bin/ruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

bash: line 1: 27920 Trace/BPT trap: 5       test-cloud version 1>&2

**Comment by jmoody** [comment]
Fixed by #68 

I strongly recommend you start using `rbenv`.
